"""empty message

Revision ID: 07815e9c1656
Revises: b48f52083ee1
Create Date: 2019-07-01 13:19:51.696392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07815e9c1656'
down_revision = 'b48f52083ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brukere',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=18), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brukere')
    # ### end Alembic commands ###
