"""empty message

Revision ID: 7e3f674de967
Revises: 07815e9c1656
Create Date: 2019-07-01 13:59:45.600436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3f674de967'
down_revision = '07815e9c1656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brukere', sa.Column('brukernavn', sa.String(length=18), nullable=True))
    op.add_column('brukere', sa.Column('passord', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'brukere', ['brukernavn'])
    op.drop_column('brukere', 'name')
    op.drop_column('brukere', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brukere', sa.Column('password', sa.VARCHAR(length=100), nullable=True))
    op.add_column('brukere', sa.Column('name', sa.VARCHAR(length=18), nullable=True))
    op.drop_constraint(None, 'brukere', type_='unique')
    op.drop_column('brukere', 'passord')
    op.drop_column('brukere', 'brukernavn')
    # ### end Alembic commands ###
