"""Changed the database for testing

Revision ID: f255f77a6484
Revises: ac03049f185c
Create Date: 2020-04-26 00:58:07.808034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f255f77a6484'
down_revision = 'ac03049f185c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medium_pizza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medium_pizza', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('informasjon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('informasjon',
    sa.Column('info_number', sa.INTEGER(), nullable=False),
    sa.Column('medium_pizza', sa.INTEGER(), nullable=True),
    sa.Column('red_sauce', sa.INTEGER(), nullable=True),
    sa.Column('white_sauce', sa.INTEGER(), nullable=True),
    sa.Column('pizza_extra_meat', sa.INTEGER(), nullable=True),
    sa.Column('pizza_extra_cheese', sa.INTEGER(), nullable=True),
    sa.Column('thai_extra_meat', sa.INTEGER(), nullable=True),
    sa.Column('thai_extra_rice', sa.INTEGER(), nullable=True),
    sa.Column('front_page_text', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('info_number')
    )
    op.drop_table('medium_pizza')
    # ### end Alembic commands ###
